### DISCUSSION TITLE
How to enable provisioned concurrency?

### DISCUSSION THREAD

**Discussion by cayter** [architect/architect#1343] [Q&A]
Does anyone here know how to extend the Cloudformation template to support provisioned concurrency? What I have tried was 

1. Extended all the `HttpLambda` Properties with the below:
```
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
```

2. Updated the HttpApi resource to have `StageName: live`.

However, the changes above just wouldn't integrate the API gateway's `live` stage correctly to the HttpLambda `live` version and show `{ "message": "not found" }`. Is there any example we can refer to for enabling provisioned concurrency? Thanks.

Note: I was following the approach recommended [here](https://aws.amazon.com/blogs/aws/new-provisioned-concurrency-for-lambda-functions/).
