### ISSUE TITLE
Configure VPC used

### ISSUE THREAD

**Issue by niwasmala** [architect/architect#1182]
**Is your feature request related to a problem? Please describe.**
I have RDS database inside VPC. I want to configure the lambda deployed to be set under right VPC. I don't find how to do this in the documentation or in github issues. Is there a way to set VPC?

**Describe the solution you'd like**
A way to configure VPC in app.arc
```
@aws
vpc
  securityGroupIds
    sg-xxx
  subnetIds
    subnet-aaa
    subnet-bbb
    subnet-ccc
```

**Describe alternatives you've considered**
This is an example how to configure in serverless framework (serverless.yml)

```
provider:
  name: aws
  vpc:
    securityGroupIds:
      - sg-xxx
    subnetIds:
      - subnet-aaa
      - subnet-bbb
      - subnet-ccc
```

**Additional context or notes**
none
