### ISSUE TITLE
Problem with node_modules in yarn 2 workspaces: Cannot find plugin 'x'

### ISSUE THREAD

**Issue by misantronic** [architect/architect#1356]
**Describe the issue**
When working with yarn 2 workspaces, node_modules are not located in the workspace-folder but in the root of the project.

architect throws an error when building:

```
- Cannot find plugin 'architect/plugin-remix'! Are you sure you have installed or created it correctly?
Error: Plugin error:
- Cannot find plugin 'architect/plugin-remix'! Are you sure you have installed or created it correctly?
    at format (/src/converter/node_modules/@architect/inventory/src/lib/error-fmt.js:15:13)
```

I traced the error back to @architect/inventory to the plugins-section:
https://github.com/architect/inventory/blob/848958571ccad74753ee336dc47364f1298287dc/src/config/pragmas/plugins.js#L103

There it checks via `cwd` where the plugin may be.
Maybe there is a way to adjust the `cwd` for this process?

**Steps to reproduce**

- Create a project where you would use yarn 2
- Add workspaces to the package.json root: `workspaces: [ "app/*" ]`
- Add a workspace where architect lives in `app/package.json`
- Install architect and a plugin
- Start the app

**Comment by HosseinAgha** [comment]
I had exactly the same issue using the remix architect template.  
Many developers use yarn v2 pnp for package management and I think this is one of `architect`'s biggest shortcomings in terms of DevX.

**Comment by ryanblock** [comment]
Possible to get more detailed steps to repro? Most (all?) the maintainers of Architect try to stay as "close to the metal" as we can as it pertains to Node.js, and that means npm (which is probably why the Yarn support has room for improvement). Thanks!

**Comment by HosseinAgha** [comment]
Hi @ryanblock,  
Thanks for the fast response.  
These are the steps:  
  1. first I created a yarn v3 monorepo using this guide (https://yarnpkg.com/getting-started/install)
  2. then I initiated a new remix-run project using `yarn dlx create-remix@latest`
  3. In the CLI wizard chose **Just the basics** and **Architect** 
  4. Then add the remix directory to yarn workspaces in the root package.json
  5. And finally call `yarn install` anywhere in the repository
  6. Now you have a yarn 3 project that uses plug-and-play for dependency resolution
  7. First If you run `yarn build` in the remix project you'll get many dependency error
  8. These are because of the architect package relying on phantom dependencies (packages that you require but are not in your package.json). Here is my `.yarnrc.yml` that resolves these mistakes (it is better to resolve them in the packages but unfortunately I don't have free time for a PR right now)
```yaml
  "@architect/architect@*":
    dependencies:
      "@architect/inventory": "*"
      "@architect/utils": "*"
  "@architect/utils@*":
    dependencies:
      "aws-sdk": "*"
  "@architect/deploy@*":
    dependencies:
      "aws-sdk": "*"
  "@architect/asap@*":
    dependencies:
      "aws-sdk": "*"
  "@architect/env@*":
    dependencies:
      "minimist": 1.2.6
```
  9. Finally after doing this you'll be able to build the project but when your run `yarn dev` which using `arc sandbox` internally you encounter many errors like (cannot find module `X` in `node_modules`)

So to conclude architect packages have 2 issues that both are not standard Node.js practice and cause modern package managers to break or throw warnings:
  1. you've required packages without directed adding them to the package that requires them ([phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/))
  2. you've required packages by providing their address in the `node_modules` instead of relying on the runtime to resolve them

Finally, I'm not sure that using yarn pnp or pnpm is a good idea in AWS lambda (definitely possible) but I know that users  will definitely use them for their local development.

**Comment by misantronic** [comment]
To everyone using yarn2 with node_modules currently facing this issue, heres a quick patch to get around the issue:

Please be aware that the path added must be relative to your existing workspace in your project.

```patch
diff --git a/src/config/pragmas/plugins.js b/src/config/pragmas/plugins.js
index 42f6f19a26f342fc217f1cd10a1e1a290edd35dc..14f1ac24246cef18f7cf6b5848042974dd95ee3c 100644
--- a/src/config/pragmas/plugins.js
+++ b/src/config/pragmas/plugins.js
@@ -106,9 +106,11 @@ function getPath (cwd, srcDir, name) {
     join(cwd, 'src', srcDir, name),
     join(cwd, 'node_modules', name),
     join(cwd, 'node_modules', `@${name}`),
+    join(cwd, '../../node_modules', `@${name}`),
   ]
   if (existsSync(paths[0]))      return paths[0]
   else if (existsSync(paths[1])) return paths[1]
   else if (existsSync(paths[2])) return paths[2]
   else if (existsSync(paths[3])) return paths[3]
+  else if (existsSync(paths[4])) return paths[4]
 }
```

**Comment by brianleroux** [comment]
Easy to also argue that yarn is also a non standard node practice! ;) 

The reason we don't add `aws-sdk` to `package.json` is that AWS Lambda Node.js runtime already has it. We recommend you run `npm i -g was-sdk` to replicate that behaviour locally. 

I don't really follow your second point as that node_modules is def a standard practice in Node and deep linking is often required to get better coldstart performance. Can you elaborate on what you expected there?

**Comment by ryanblock** [comment]
l have some thoughts / followups on some of the other points from this thread, but we can definitely minimize the phantom dependency impact, so as of 10.5.3 I think you should now be able to use the following in your `.yarnrc.yml` without issue (but if not, please do let us know!):

```yml
packageExtensions:
  "@architect/asap@*":
    dependencies:
      "aws-sdk": "*"
  "@architect/deploy@*":
    dependencies:
      "aws-sdk": "*"
  "@architect/functions@*":
    dependencies:
      "aws-sdk": "*"
  "@architect/inventory@*":
    dependencies:
      "aws-sdk": "*"
  "@architect/package@*":
    dependencies:
      "aws-sdk": "*"
  "@architect/utils@*":
    dependencies:
      "aws-sdk": "*"
```

Moreover, if their syntax supports npm namespaced wildcards, this should reduce that quite a bit:

```yml
packageExtensions:
  "@architect/*@*":
    dependencies:
      "aws-sdk": "*"
```

More soon!
