### ISSUE TITLE
Lambda layers definition in the arc.yaml file format

### ISSUE THREAD

**Issue by sbernardello** [architect/architect#1436]
**Describe the issue**

Trying to implement the yaml version of the app.arc configuration (app.yml) but experiencing some issues about lambda layers definition.
Running any command after adding the lambda layer results in a  `Configuration errors: - Invalid ARN (arc.yml):` for each function defined in the application.

**Steps to reproduce**

This is how arc.yml file is set:

```yaml
app: "application"

aws:
  runtime: python3.9
  timeout: 30
  layers:
    - "arn:aws:lambda:us-east-1:1234567890123:layer:layername:1"
```

**Additional context**
We have the same error when using JSON file format (arc.json)
The lambda layer we're testing works fine on the standard flat app.arc file.
