### ISSUE TITLE
Add support for DynamoDB encryption

### ISSUE THREAD

**Issue by defionscode** [architect/architect#584]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**

something like

```
# for customer-managed
@tables
myTable
  encrypt 'mycmk'

# for aws-managed
@tables
myTable
  encrypt true
```

The CloudFormation/SAM would need this addition

```yaml
Properties:
    SSESpecification: 
      KMSMasterKeyId : String # Set to the string value of `encrypt` if string type 
      SSEEnabled : Boolean # Set to true if `encrypt` is `true` (not a string or `false`)
      SSEType : String # Set to `KMS` if `encrypt` is a string value, otherwise omit it
```

**Describe alternatives you've considered**
A custom macro works as an interim solution, but I think it's reasonable to make this a native feature.
